# Generated by Django 4.1.1 on 2022-09-21 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('day', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2, primary_key=True, serialize=False)),
                ('hours', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24)])),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('start', models.DateField(verbose_name='Start date')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('estimated_duration', models.IntegerField(default=0)),
                ('actual_duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('OG', 'On going'), ('C', 'Completed')], default='NS', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.category')),
            ],
        ),
    ]
