# Generated by Django 4.1.1 on 2022-09-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('start', models.DateField()),
                ('deadline', models.DateField()),
                ('estimated_duration', models.IntegerField(default=0)),
                ('actual_duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('NS', 'Not started'), ('OG', 'On going'), ('C', 'Completed')], default='NS', max_length=2)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.category')),
            ],
        ),
    ]
