# Generated by Django 4.1.1 on 2022-09-28 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='friday',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Friday'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='monday',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='saturday',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Saturday'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='sunday',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Sunday'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='thursday',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Thursday'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='tuesday',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Tuesday'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='wednesday',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)], verbose_name='Wednesday'),
        ),
    ]
