# Generated by Django 4.1.1 on 2022-09-13 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('day', models.CharField(choices=[('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=2, primary_key=True, serialize=False)),
                ('hours', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(24)])),
            ],
        ),
    ]
